stages:
 - build_and_deploy

build_and_deploy:
 stage: build_and_deploy
 image: ubuntu:latest
 script:
   - apt-get update && apt-get install -y openssh-client
   - mkdir /root/.ssh
   - echo "$SSH_PRIVATE_KEY_NODE_DEV" | tr -d '\r' > /root/.ssh/id_rsa
   - chmod 400 /root/.ssh/id_rsa
   - scp -i "/root/.ssh/id_rsa" -o StrictHostKeyChecking=no ./deploy_dev_script.sh ec2-user@52.91.232.215:./
   - ssh -i "/root/.ssh/id_rsa" -o StrictHostKeyChecking=no ec2-user@52.91.232.215 "bash -s" < ./deploy_dev_script.sh "$CI_PROJECT_NAME" "$CI_COMMIT_SHORT_SHA" "$CI_COMMIT_REF_NAME"

 only:
  - dev
    