stages:
 - build_and_deploy

build_and_deploy:
 stage: build_and_deploy
 image: ubuntu:latest
 script:
   - apt-get update && apt-get install -y openssh-client
   - mkdir /root/.ssh
   - echo "$SSH_PRIVATE_KEY_NODE_DEV" | tr -d '\r' > /root/.ssh/id_rsa
   - chmod 400 /root/.ssh/id_rsa
   - scp -i "/root/.ssh/id_rsa" -o StrictHostKeyChecking=no ./deploy_main_script.sh ubuntu@35.170.211.159:./
   - ssh -i "/root/.ssh/id_rsa" -o StrictHostKeyChecking=no ec2-user@123.123.123.123 "bash -s" < ./deploy_main_script.sh "$CI_PROJECT_NAME" "$CI_COMMIT_SHORT_SHA" "$CI_COMMIT_REF_NAME"

 only:
  - main
    